<a href="https://colab.research.google.com/github/Trexroy1010/Machiene-Learning-Projects/blob/main/intover_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#we will use, rfc, svm and simple ann for this,

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e7/sample_submission.csv
/kaggle/input/playground-series-s5e7/train.csv
/kaggle/input/playground-series-s5e7/test.csv

In [ ]:
df = pd.read_csv('/kaggle/input/playground-series-s5e7/train.csv')
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert

In [ ]:
df.info

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

<bound method DataFrame.info of           id  Time_spent_Alone Stage_fear  Social_event_attendance  \
0          0               0.0         No                      6.0
1          1               1.0         No                      7.0
2          2               6.0        Yes                      1.0
3          3               3.0         No                      7.0
4          4               1.0         No                      4.0
...      ...               ...        ...                      ...
18519  18519               3.0         No                      7.0
18520  18520               1.0        NaN                      6.0
18521  18521               7.0        Yes                      1.0
18522  18522               NaN        Yes                      1.0
18523  18523               1.0         No                      8.0

       Going_outside Drained_after_socializing  Friends_circle_size  \
0                4.0                        No                 15.0
1                3.0                        No                 10.0
2                0.0                       NaN                  3.0
3                3.0                        No                 11.0
4                4.0                        No                 13.0
...              ...                       ...                  ...
18519            3.0                        No                  9.0
18520            7.0                        No                  6.0
18521            1.0                       Yes                  1.0
18522            0.0                       Yes                  5.0
18523            6.0                        No                  4.0

       Post_frequency Personality
0                 5.0   Extrovert
1                 8.0   Extrovert
2                 0.0   Introvert
3                 5.0   Extrovert
4                 NaN   Extrovert
...               ...         ...
18519             7.0   Extrovert
18520             5.0   Extrovert
18521             NaN   Introvert
18522             2.0   Introvert
18523             7.0   Extrovert

[18524 rows x 9 columns]>

In [ ]:
df.isnull().sum

<bound method DataFrame.sum of           id  Time_spent_Alone  Stage_fear  Social_event_attendance  \
0      False             False       False                    False
1      False             False       False                    False
2      False             False       False                    False
3      False             False       False                    False
4      False             False       False                    False
...      ...               ...         ...                      ...
18519  False             False       False                    False
18520  False             False        True                    False
18521  False             False       False                    False
18522  False              True       False                    False
18523  False             False       False                    False

       Going_outside  Drained_after_socializing  Friends_circle_size  \
0              False                      False                False
1              False                      False                False
2              False                       True                False
3              False                      False                False
4              False                      False                False
...              ...                        ...                  ...
18519          False                      False                False
18520          False                      False                False
18521          False                      False                False
18522          False                      False                False
18523          False                      False                False

       Post_frequency  Personality
0               False        False
1               False        False
2               False        False
3               False        False
4                True        False
...               ...          ...
18519           False        False
18520           False        False
18521            True        False
18522           False        False
18523           False        False

[18524 rows x 9 columns]>

In [ ]:
df.dropna()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
7,7,2.0,No,8.0,3.0,No,4.0,5.0,Extrovert
9,9,1.0,No,8.0,6.0,No,14.0,9.0,Extrovert
...,...,...,...,...,...,...,...,...,...
18509,18509,1.0,No,3.0,4.0,No,15.0,4.0,Extrovert
18511,18511,0.0,No,4.0,5.0,No,11.0,4.0,Extrovert
18514,18514,6.0,No,5.0,3.0,No,10.0,4.0,Extrovert
18519,18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert
18523,18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert

In [ ]:
df_encoded = pd.get_dummies(data = df, columns = ['Stage_fear', 'Drained_after_socializing', 'Personality'], dtype = int)

In [ ]:
df_encoded.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency,Stage_fear_No,Stage_fear_Yes,Drained_after_socializing_No,Drained_after_socializing_Yes,Personality_Extrovert,Personality_Introvert
0,0,0.0,6.0,4.0,15.0,5.0,1,0,1,0,1,0
1,1,1.0,7.0,3.0,10.0,8.0,1,0,1,0,1,0
2,2,6.0,1.0,0.0,3.0,0.0,0,1,0,0,0,1
3,3,3.0,7.0,3.0,11.0,5.0,1,0,1,0,1,0
4,4,1.0,4.0,4.0,13.0,NaN,1,0,1,0,1,0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df_encoded.columns

Index(['id', 'Time_spent_Alone', 'Social_event_attendance', 'Going_outside',
       'Friends_circle_size', 'Post_frequency', 'Stage_fear_No',
       'Stage_fear_Yes', 'Drained_after_socializing_No',
       'Drained_after_socializing_Yes', 'Personality_Extrovert',
       'Personality_Introvert'],
      dtype='object')

In [ ]:
df_encoded.dropna(inplace = True)

In [ ]:
X = df_encoded[['id', 'Time_spent_Alone','Social_event_attendance','Going_outside', 'Friends_circle_size', 'Post_frequency', 'Stage_fear_Yes', 'Drained_after_socializing_Yes']]

In [ ]:
y = df_encoded['Personality_Extrovert']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 43)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier(n_estimators = 100, random_state = 42)

In [ ]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [ ]:
print(f"MSE : {mse}")
print(f"R2 : {r2}")

MSE : 0.03142857142857143
R2 : 0.8182306981564375

In [ ]:
from sklearn.svm import SVC

In [ ]:
model2 = SVC()

In [ ]:
model2.fit(X_train, y_train)

SVC()

In [ ]:
y_pred2 = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
score = accuracy_score(y_test, y_pred2)

In [ ]:
print(score)

0.9685714285714285

AS OF NOW, SVC gave us 96.8%, and RANDOM FOREST HAS GIVEN US = 81.82%, next i will try ANN and see what happens

In [ ]:
import tensorflow as tf

2025-08-13 18:45:34.372309: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1755110734.589571      36 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1755110734.654122      36 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)

In [ ]:
X_test = sc.fit_transform(X_test)

In [ ]:
X_train.shape

(8981, 8)

In [ ]:
X_train

array([[-0.30600696,  0.00304514,  1.69944015, ...,  1.01250967,
        -0.47547354, -0.47688113],
       [-1.25720931,  2.05417746, -1.22094674, ..., -1.4395665 ,
        -0.47547354,  2.09695865],
       [-1.45607151,  1.0286113 , -1.5859951 , ..., -0.38867671,
         2.10316646,  2.09695865],
       ...,
       [ 0.42815257,  0.68675591, -1.5859951 , ..., -1.0892699 ,
         2.10316646,  2.09695865],
       [-1.11120209, -0.68066563,  0.60429507, ..., -0.03838012,
        -0.47547354, -0.47688113],
       [-0.81206535,  0.00304514,  0.96934343, ..., -0.73897331,
        -0.47547354, -0.47688113]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU, PReLU, ELU, ReLU, Dropout

In [ ]:
classifier = Sequential()

In [ ]:
classifier.add(Dense(units = 12, activation = 'relu', input_shape = (X_train.shape[1],)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-08-13 18:58:11.594892: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [ ]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [ ]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [ ]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [ ]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [ ]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [ ]:
#since it's a binary classification, we use sigmoid function
classifier.add(Dense(1, activation = 'sigmoid'))

In [ ]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model_history = classifier.fit(X_train,y_train, validation_split = 0.33, batch_size = 100, epochs = 100)

Epoch 1/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7647 - loss: 0.6328 - val_accuracy: 0.7578 - val_loss: 0.4215
Epoch 2/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7702 - loss: 0.3465 - val_accuracy: 0.7578 - val_loss: 0.2840
Epoch 3/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7660 - loss: 0.2703 - val_accuracy: 0.9464 - val_loss: 0.2696
Epoch 4/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9611 - loss: 0.2424 - val_accuracy: 0.9639 - val_loss: 0.2609
Epoch 5/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9651 - loss: 0.2510 - val_accuracy: 0.9636 - val_loss: 0.2529
Epoch 6/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9635 - loss: 0.2390 - val_accuracy: 0.9649 - val_loss: 0.2457
Epoch 7/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9646 - loss: 0.2334 - val_accuracy: 0.9642 - val_loss: 0.2396
Epoch 8/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9662 - loss: 0.2242 - val_accuracy: 0.9636 - val_loss: 0.2343
Epoch 9/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9677 - loss: 0.2141 - val_accuracy: 0.9636 - val_loss: 0.2293
Epoch 10/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9640 - loss: 0.2242 - val_accuracy: 0.9636 - val_loss: 0.2252
Epoch 11/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9641 - loss: 0.2115 - val_accuracy: 0.9636 - val_loss: 0.2209
Epoch 12/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9634 - loss: 0.2099 - val_accuracy: 0.9636 - val_loss: 0.2168
Epoch 13/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9676 - loss: 0.2027 - val_accuracy: 0.9639 - val_loss: 0.2132
Epoch 14/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9690 - loss: 0.1939 - val_accuracy: 0.9642 - val_loss: 0.2099
Epoch 15/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9651 - loss: 0.2016 - val_accuracy: 0.9639 - val_loss: 0.2068
Epoch 16/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9665 - loss: 0.1945 - val_accuracy: 0.9642 - val_loss: 0.2033
Epoch 17/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9664 - loss: 0.1970 - val_accuracy: 0.9642 - val_loss: 0.2008
Epoch 18/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9680 - loss: 0.1843 - val_accuracy: 0.9642 - val_loss: 0.1976
Epoch 19/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9712 - loss: 0.1716 - val_accuracy: 0.9642 - val_loss: 0.1952
Epoch 20/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9677 - loss: 0.1787 - val_accuracy: 0.9642 - val_loss: 0.1923
Epoch 21/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9645 - loss: 0.1785 - val_accuracy: 0.9642 - val_loss: 0.1900
Epoch 22/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9712 - loss: 0.1685 - val_accuracy: 0.9642 - val_loss: 0.1879
Epoch 23/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9694 - loss: 0.1714 - val_accuracy: 0.9642 - val_loss: 0.1857
Epoch 24/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9688 - loss: 0.1699 - val_accuracy: 0.9642 - val_loss: 0.1836
Epoch 25/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9676 - loss: 0.1674 - val_accuracy: 0.9639 - val_loss: 0.1818
Epoch 26/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9623 - loss: 0.1803 - val_accuracy: 0.9639 - val_loss: 0.1818
Epoch 27/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9692 - loss: 0.1596 - val_accuracy: 0.9642 - val_loss: 0.1787
Epoch 28/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9657 - loss: 0.1647 - val_accuracy: 0.9642 - val_loss: 0.1775
Epoch 29/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9647 - loss: 0.1733 - val_accuracy: 0.9636 - val_loss: 0.1751
Epoch 30/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9691 - loss: 0.1554 - val_accuracy: 0.9636 - val_loss: 0.1736
Epoch 31/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9665 - loss: 0.1638 - val_accuracy: 0.9639 - val_loss: 0.1723
Epoch 32/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9668 - loss: 0.1602 - val_accuracy: 0.9642 - val_loss: 0.1712
Epoch 33/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9719 - loss: 0.1471 - val_accuracy: 0.9642 - val_loss: 0.1706
Epoch 34/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9684 - loss: 0.1597 - val_accuracy: 0.9632 - val_loss: 0.1700
Epoch 35/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9674 - loss: 0.1568 - val_accuracy: 0.9632 - val_loss: 0.1679
Epoch 36/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9675 - loss: 0.1531 - val_accuracy: 0.9636 - val_loss: 0.1671
Epoch 37/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9652 - loss: 0.1542 - val_accuracy: 0.9632 - val_loss: 0.1661
Epoch 38/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9657 - loss: 0.1549 - val_accuracy: 0.9626 - val_loss: 0.1654
Epoch 39/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9698 - loss: 0.1428 - val_accuracy: 0.9632 - val_loss: 0.1641
Epoch 40/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9676 - loss: 0.1478 - val_accuracy: 0.9629 - val_loss: 0.1634
Epoch 41/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9703 - loss: 0.1425 - val_accuracy: 0.9632 - val_loss: 0.1630
Epoch 42/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9641 - loss: 0.1511 - val_accuracy: 0.9626 - val_loss: 0.1621
Epoch 43/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9652 - loss: 0.1549 - val_accuracy: 0.9629 - val_loss: 0.1623
Epoch 44/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9678 - loss: 0.1436 - val_accuracy: 0.9626 - val_loss: 0.1607
Epoch 45/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9672 - loss: 0.1467 - val_accuracy: 0.9626 - val_loss: 0.1605
Epoch 46/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9670 - loss: 0.1458 - val_accuracy: 0.9626 - val_loss: 0.1595
Epoch 47/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9689 - loss: 0.1412 - val_accuracy: 0.9629 - val_loss: 0.1602
Epoch 48/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9699 - loss: 0.1374 - val_accuracy: 0.9626 - val_loss: 0.1588
Epoch 49/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9650 - loss: 0.1496 - val_accuracy: 0.9632 - val_loss: 0.1582
Epoch 50/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9696 - loss: 0.1319 - val_accuracy: 0.9629 - val_loss: 0.1578
Epoch 51/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9683 - loss: 0.1379 - val_accuracy: 0.9632 - val_loss: 0.1571
Epoch 52/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9677 - loss: 0.1431 - val_accuracy: 0.9632 - val_loss: 0.1570
Epoch 53/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9668 - loss: 0.1421 - val_accuracy: 0.9632 - val_loss: 0.1568
Epoch 54/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9642 - loss: 0.1521 - val_accuracy: 0.9636 - val_loss: 0.1568
Epoch 55/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9707 - loss: 0.1307 - val_accuracy: 0.9632 - val_loss: 0.1560
Epoch 56/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9699 - loss: 0.1318 - val_accuracy: 0.9632 - val_loss: 0.1555
Epoch 57/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9693 - loss: 0.1332 - val_accuracy: 0.9636 - val_loss: 0.1552
Epoch 58/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9645 - loss: 0.1419 - val_accuracy: 0.9632 - val_loss: 0.1557
Epoch 59/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9704 - loss: 0.1265 - val_accuracy: 0.9632 - val_loss: 0.1546
Epoch 60/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9622 - loss: 0.1505 - val_accuracy: 0.9629 - val_loss: 0.1563
Epoch 61/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9691 - loss: 0.1276 - val_accuracy: 0.9629 - val_loss: 0.1540
Epoch 62/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9705 - loss: 0.1259 - val_accuracy: 0.9632 - val_loss: 0.1541
Epoch 63/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9648 - loss: 0.1404 - val_accuracy: 0.9629 - val_loss: 0.1538
Epoch 64/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9695 - loss: 0.1320 - val_accuracy: 0.9636 - val_loss: 0.1533
Epoch 65/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9667 - loss: 0.1367 - val_accuracy: 0.9636 - val_loss: 0.1534
Epoch 66/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9665 - loss: 0.1380 - val_accuracy: 0.9632 - val_loss: 0.1540
Epoch 67/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9667 - loss: 0.1368 - val_accuracy: 0.9632 - val_loss: 0.1532
Epoch 68/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9695 - loss: 0.1284 - val_accuracy: 0.9629 - val_loss: 0.1528
Epoch 69/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9658 - loss: 0.1424 - val_accuracy: 0.9629 - val_loss: 0.1529
Epoch 70/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9682 - loss: 0.1326 - val_accuracy: 0.9632 - val_loss: 0.1539
Epoch 71/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9705 - loss: 0.1241 - val_accuracy: 0.9632 - val_loss: 0.1527
Epoch 72/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9682 - loss: 0.1294 - val_accuracy: 0.9632 - val_loss: 0.1520
Epoch 73/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9655 - loss: 0.1369 - val_accuracy: 0.9632 - val_loss: 0.1540
Epoch 74/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9697 - loss: 0.1264 - val_accuracy: 0.9632 - val_loss: 0.1534
Epoch 75/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9652 - loss: 0.1411 - val_accuracy: 0.9632 - val_loss: 0.1549
Epoch 76/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9708 - loss: 0.1220 - val_accuracy: 0.9632 - val_loss: 0.1521
Epoch 77/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9653 - loss: 0.1351 - val_accuracy: 0.9636 - val_loss: 0.1529
Epoch 78/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9702 - loss: 0.1270 - val_accuracy: 0.9632 - val_loss: 0.1519
Epoch 79/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9664 - loss: 0.1375 - val_accuracy: 0.9632 - val_loss: 0.1520
Epoch 80/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9691 - loss: 0.1266 - val_accuracy: 0.9636 - val_loss: 0.1518
Epoch 81/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9664 - loss: 0.1318 - val_accuracy: 0.9629 - val_loss: 0.1521
Epoch 82/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9664 - loss: 0.1346 - val_accuracy: 0.9632 - val_loss: 0.1523
Epoch 83/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9690 - loss: 0.1271 - val_accuracy: 0.9632 - val_loss: 0.1528
Epoch 84/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9692 - loss: 0.1232 - val_accuracy: 0.9636 - val_loss: 0.1525
Epoch 85/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9661 - loss: 0.1375 - val_accuracy: 0.9629 - val_loss: 0.1525
Epoch 86/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9702 - loss: 0.1241 - val_accuracy: 0.9632 - val_loss: 0.1518
Epoch 87/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9663 - loss: 0.1337 - val_accuracy: 0.9629 - val_loss: 0.1523
Epoch 88/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9680 - loss: 0.1308 - val_accuracy: 0.9629 - val_loss: 0.1530
Epoch 89/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9678 - loss: 0.1310 - val_accuracy: 0.9626 - val_loss: 0.1525
Epoch 90/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9715 - loss: 0.1189 - val_accuracy: 0.9632 - val_loss: 0.1531
Epoch 91/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9693 - loss: 0.1242 - val_accuracy: 0.9632 - val_loss: 0.1528
Epoch 92/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9670 - loss: 0.1280 - val_accuracy: 0.9632 - val_loss: 0.1524
Epoch 93/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9686 - loss: 0.1272 - val_accuracy: 0.9632 - val_loss: 0.1533
Epoch 94/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9683 - loss: 0.1275 - val_accuracy: 0.9626 - val_loss: 0.1544
Epoch 95/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9688 - loss: 0.1287 - val_accuracy: 0.9632 - val_loss: 0.1533
Epoch 96/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9711 - loss: 0.1185 - val_accuracy: 0.9622 - val_loss: 0.1529
Epoch 97/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9690 - loss: 0.1277 - val_accuracy: 0.9632 - val_loss: 0.1535
Epoch 98/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9695 - loss: 0.1213 - val_accuracy: 0.9632 - val_loss: 0.1528
Epoch 99/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9697 - loss: 0.1263 - val_accuracy: 0.9632 - val_loss: 0.1569
Epoch 100/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9641 - loss: 0.1439 - val_accuracy: 0.9632 - val_loss: 0.1537

In [ ]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [ ]:
y_pred2 = classifier.predict(X_test)
y_pred2 = (y_pred>0.5)

121/121 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred2)

In [ ]:
cm

array([[ 783,   73],
       [  49, 2945]])

In [ ]:
score2 = accuracy_score(y_pred2, y_test)

In [ ]:
score2

0.9683116883116883

so we got 96.83% accuracy with ann, 0.02 difference with the SVM, we SVM IS better