<a href="https://colab.research.google.com/github/Trexroy1010/Machiene-Learning-Projects/blob/main/stress_monitoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **stress_monitoring dataset done with SVC and simple ann**

# Don't use more than 100 epochs for this, it will result in overfitting and 100% accuracy

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
df = pd.read_csv('/content/StressLevelDataset.csv')
df.head(5)

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
0,14,20,0,11,2,1,2,4,2,3,...,2,3,2,3,3,2,3,3,2,1
1,15,8,1,15,5,3,1,4,3,1,...,2,1,4,1,5,1,4,5,5,2
2,12,18,1,14,2,1,2,2,2,2,...,2,2,3,3,2,2,3,2,2,1
3,16,12,1,15,4,3,1,3,4,2,...,2,2,4,1,4,1,4,4,5,2
4,16,28,0,7,2,3,5,1,3,2,...,3,4,3,1,2,1,5,0,5,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   anxiety_level                 1100 non-null   int64
 1   self_esteem                   1100 non-null   int64
 2   mental_health_history         1100 non-null   int64
 3   depression                    1100 non-null   int64
 4   headache                      1100 non-null   int64
 5   blood_pressure                1100 non-null   int64
 6   sleep_quality                 1100 non-null   int64
 7   breathing_problem             1100 non-null   int64
 8   noise_level                   1100 non-null   int64
 9   living_conditions             1100 non-null   int64
 10  safety                        1100 non-null   int64
 11  basic_needs                   1100 non-null   int64
 12  academic_performance          1100 non-null   int64
 13  study_load                    1100 non-null   int64
 14  teacher_student_relationship  1100 non-null   int64
 15  future_career_concerns        1100 non-null   int64
 16  social_support                1100 non-null   int64
 17  peer_pressure                 1100 non-null   int64
 18  extracurricular_activities    1100 non-null   int64
 19  bullying                      1100 non-null   int64
 20  stress_level                  1100 non-null   int64
dtypes: int64(21)
memory usage: 180.6 KB

In [6]:
df.dropna()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
0,14,20,0,11,2,1,2,4,2,3,...,2,3,2,3,3,2,3,3,2,1
1,15,8,1,15,5,3,1,4,3,1,...,2,1,4,1,5,1,4,5,5,2
2,12,18,1,14,2,1,2,2,2,2,...,2,2,3,3,2,2,3,2,2,1
3,16,12,1,15,4,3,1,3,4,2,...,2,2,4,1,4,1,4,4,5,2
4,16,28,0,7,2,3,5,1,3,2,...,3,4,3,1,2,1,5,0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,11,17,0,14,3,1,3,2,2,2,...,3,2,2,2,3,3,2,3,3,1
1096,9,12,0,8,0,3,0,0,0,1,...,4,0,1,1,1,1,3,4,3,2
1097,4,26,0,3,1,2,5,2,2,3,...,4,5,1,4,1,3,1,2,1,0
1098,21,0,1,19,5,3,1,4,3,1,...,1,2,5,1,4,1,4,4,4,2
1099,18,6,1,15,3,3,0,3,3,0,...,3,3,4,3,3,1,5,1,4,2

In [7]:
X = df.iloc[:, 0:20]
y = df['stress_level']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 42)

In [10]:
from sklearn.svm import SVC

In [11]:
model = SVC()

In [12]:
model.fit(X_train, y_train)

SVC()

In [13]:
y_pred = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
score = accuracy_score(y_test,y_pred)

In [16]:
print(score)

0.9022727272727272

In [17]:
import tensorflow as tf

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,  ReLU

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()

In [21]:
X_train.shape

(660, 20)

In [22]:
X_train_sc = sc.fit_transform(X_train)

In [23]:
X_test_sc = sc.fit_transform(X_test)

In [24]:
X_train_sc

array([[-0.03694124,  0.07769734,  0.98496155, ..., -0.53940602,
         0.12269957, -0.4201299 ],
       [-1.34599991,  1.17577539, -1.01526806, ..., -0.53940602,
        -0.58148925, -1.06799376],
       [-0.03694124, -1.02038071, -1.01526806, ...,  1.53442684,
        -1.28567806, -0.4201299 ],
       ...,
       [ 0.6175881 , -1.78903534,  0.98496155, ...,  1.53442684,
         0.82688838,  1.52346168],
       [-0.03694124, -0.03211046, -1.01526806, ..., -0.53940602,
         0.12269957,  0.22773396],
       [-0.20057357, -0.25172607,  0.98496155, ..., -0.53940602,
         0.12269957, -0.4201299 ]])

In [25]:
num_class = df['stress_level'].nunique()

In [26]:
num_class

3

In [27]:
classifier = Sequential()

In [28]:
classifier.add(Dense(units = 20, activation = 'relu', input_shape = (X_train_sc.shape[1],)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [30]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [31]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [32]:
classifier.add(Dense(units = 7, activation = 'relu'))

In [33]:
classifier.add(Dense(num_class, activation = 'softmax'))

In [34]:
classifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [38]:
model_history = classifier.fit(X_train_sc, y_train, validation_split = 0.33, batch_size = 100, epochs = 300)

Epoch 1/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9659 - loss: 0.1081 - val_accuracy: 0.8670 - val_loss: 0.3178
Epoch 2/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9728 - loss: 0.0901 - val_accuracy: 0.8670 - val_loss: 0.3194
Epoch 3/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9698 - loss: 0.1005 - val_accuracy: 0.8670 - val_loss: 0.3200
Epoch 4/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9599 - loss: 0.1021 - val_accuracy: 0.8624 - val_loss: 0.3213
Epoch 5/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9747 - loss: 0.0890 - val_accuracy: 0.8624 - val_loss: 0.3220
Epoch 6/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9657 - loss: 0.1024 - val_accuracy: 0.8624 - val_loss: 0.3219
Epoch 7/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9597 - loss: 0.1074 - val_accuracy: 0.8624 - val_loss: 0.3233
Epoch 8/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9648 - loss: 0.0998 - val_accuracy: 0.8578 - val_loss: 0.3255
Epoch 9/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9736 - loss: 0.0834 - val_accuracy: 0.8578 - val_loss: 0.3280
Epoch 10/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9714 - loss: 0.0869 - val_accuracy: 0.8624 - val_loss: 0.3283
Epoch 11/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9700 - loss: 0.0893 - val_accuracy: 0.8670 - val_loss: 0.3302
Epoch 12/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9660 - loss: 0.0855 - val_accuracy: 0.8670 - val_loss: 0.3330
Epoch 13/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9710 - loss: 0.0843 - val_accuracy: 0.8670 - val_loss: 0.3365
Epoch 14/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9764 - loss: 0.0747 - val_accuracy: 0.8624 - val_loss: 0.3386
Epoch 15/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9616 - loss: 0.1008 - val_accuracy: 0.8716 - val_loss: 0.3365
Epoch 16/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9802 - loss: 0.0785 - val_accuracy: 0.8761 - val_loss: 0.3376
Epoch 17/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9782 - loss: 0.0801 - val_accuracy: 0.8716 - val_loss: 0.3411
Epoch 18/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9793 - loss: 0.0836 - val_accuracy: 0.8716 - val_loss: 0.3445
Epoch 19/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9795 - loss: 0.0800 - val_accuracy: 0.8716 - val_loss: 0.3475
Epoch 20/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9784 - loss: 0.0839 - val_accuracy: 0.8716 - val_loss: 0.3506
Epoch 21/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9859 - loss: 0.0698 - val_accuracy: 0.8761 - val_loss: 0.3526
Epoch 22/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9801 - loss: 0.0788 - val_accuracy: 0.8761 - val_loss: 0.3530
Epoch 23/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9892 - loss: 0.0678 - val_accuracy: 0.8761 - val_loss: 0.3551
Epoch 24/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9849 - loss: 0.0783 - val_accuracy: 0.8807 - val_loss: 0.3562
Epoch 25/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9872 - loss: 0.0740 - val_accuracy: 0.8761 - val_loss: 0.3593
Epoch 26/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9833 - loss: 0.0614 - val_accuracy: 0.8761 - val_loss: 0.3615
Epoch 27/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9847 - loss: 0.0721 - val_accuracy: 0.8761 - val_loss: 0.3625
Epoch 28/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9824 - loss: 0.0673 - val_accuracy: 0.8761 - val_loss: 0.3631
Epoch 29/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.0705 - val_accuracy: 0.8761 - val_loss: 0.3669
Epoch 30/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9824 - loss: 0.0663 - val_accuracy: 0.8761 - val_loss: 0.3695
Epoch 31/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9876 - loss: 0.0579 - val_accuracy: 0.8761 - val_loss: 0.3719
Epoch 32/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9872 - loss: 0.0574 - val_accuracy: 0.8761 - val_loss: 0.3730
Epoch 33/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9781 - loss: 0.0773 - val_accuracy: 0.8761 - val_loss: 0.3731
Epoch 34/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9889 - loss: 0.0676 - val_accuracy: 0.8761 - val_loss: 0.3751
Epoch 35/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9916 - loss: 0.0614 - val_accuracy: 0.8761 - val_loss: 0.3779
Epoch 36/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9882 - loss: 0.0671 - val_accuracy: 0.8761 - val_loss: 0.3811
Epoch 37/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9894 - loss: 0.0599 - val_accuracy: 0.8716 - val_loss: 0.3844
Epoch 38/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9878 - loss: 0.0607 - val_accuracy: 0.8716 - val_loss: 0.3849
Epoch 39/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9921 - loss: 0.0530 - val_accuracy: 0.8716 - val_loss: 0.3860
Epoch 40/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9916 - loss: 0.0507 - val_accuracy: 0.8716 - val_loss: 0.3891
Epoch 41/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9844 - loss: 0.0655 - val_accuracy: 0.8761 - val_loss: 0.3906
Epoch 42/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9871 - loss: 0.0658 - val_accuracy: 0.8761 - val_loss: 0.3906
Epoch 43/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9856 - loss: 0.0600 - val_accuracy: 0.8761 - val_loss: 0.3945
Epoch 44/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9871 - loss: 0.0565 - val_accuracy: 0.8761 - val_loss: 0.3996
Epoch 45/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 0.9878 - loss: 0.0559 - val_accuracy: 0.8761 - val_loss: 0.4010
Epoch 46/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9929 - loss: 0.0453 - val_accuracy: 0.8761 - val_loss: 0.4032
Epoch 47/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9864 - loss: 0.0659 - val_accuracy: 0.8761 - val_loss: 0.4064
Epoch 48/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.9871 - loss: 0.0523 - val_accuracy: 0.8761 - val_loss: 0.4098
Epoch 49/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9900 - loss: 0.0500 - val_accuracy: 0.8761 - val_loss: 0.4118
Epoch 50/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.9840 - loss: 0.0554 - val_accuracy: 0.8761 - val_loss: 0.4135
Epoch 51/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9914 - loss: 0.0460 - val_accuracy: 0.8807 - val_loss: 0.4140
Epoch 52/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9898 - loss: 0.0526 - val_accuracy: 0.8807 - val_loss: 0.4176
Epoch 53/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9926 - loss: 0.0412 - val_accuracy: 0.8807 - val_loss: 0.4187
Epoch 54/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.9861 - loss: 0.0528 - val_accuracy: 0.8807 - val_loss: 0.4188
Epoch 55/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9886 - loss: 0.0550 - val_accuracy: 0.8807 - val_loss: 0.4236
Epoch 56/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9878 - loss: 0.0525 - val_accuracy: 0.8807 - val_loss: 0.4263
Epoch 57/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9904 - loss: 0.0468 - val_accuracy: 0.8807 - val_loss: 0.4285
Epoch 58/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9891 - loss: 0.0487 - val_accuracy: 0.8807 - val_loss: 0.4308
Epoch 59/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9916 - loss: 0.0415 - val_accuracy: 0.8807 - val_loss: 0.4350
Epoch 60/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9889 - loss: 0.0462 - val_accuracy: 0.8807 - val_loss: 0.4402
Epoch 61/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9906 - loss: 0.0423 - val_accuracy: 0.8807 - val_loss: 0.4443
Epoch 62/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9805 - loss: 0.0583 - val_accuracy: 0.8807 - val_loss: 0.4472
Epoch 63/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9896 - loss: 0.0425 - val_accuracy: 0.8807 - val_loss: 0.4515
Epoch 64/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9886 - loss: 0.0406 - val_accuracy: 0.8807 - val_loss: 0.4514
Epoch 65/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9928 - loss: 0.0388 - val_accuracy: 0.8807 - val_loss: 0.4537
Epoch 66/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9942 - loss: 0.0305 - val_accuracy: 0.8807 - val_loss: 0.4579
Epoch 67/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9873 - loss: 0.0453 - val_accuracy: 0.8807 - val_loss: 0.4602
Epoch 68/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9914 - loss: 0.0373 - val_accuracy: 0.8807 - val_loss: 0.4639
Epoch 69/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9903 - loss: 0.0366 - val_accuracy: 0.8761 - val_loss: 0.4662
Epoch 70/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9920 - loss: 0.0392 - val_accuracy: 0.8761 - val_loss: 0.4679
Epoch 71/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9856 - loss: 0.0444 - val_accuracy: 0.8761 - val_loss: 0.4712
Epoch 72/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9934 - loss: 0.0354 - val_accuracy: 0.8761 - val_loss: 0.4756
Epoch 73/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9941 - loss: 0.0308 - val_accuracy: 0.8761 - val_loss: 0.4777
Epoch 74/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9924 - loss: 0.0322 - val_accuracy: 0.8761 - val_loss: 0.4782
Epoch 75/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9908 - loss: 0.0357 - val_accuracy: 0.8761 - val_loss: 0.4805
Epoch 76/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9951 - loss: 0.0361 - val_accuracy: 0.8761 - val_loss: 0.4832
Epoch 77/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9907 - loss: 0.0406 - val_accuracy: 0.8761 - val_loss: 0.4837
Epoch 78/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9963 - loss: 0.0317 - val_accuracy: 0.8761 - val_loss: 0.4865
Epoch 79/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9963 - loss: 0.0285 - val_accuracy: 0.8761 - val_loss: 0.4884
Epoch 80/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9932 - loss: 0.0372 - val_accuracy: 0.8761 - val_loss: 0.4908
Epoch 81/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9946 - loss: 0.0369 - val_accuracy: 0.8761 - val_loss: 0.4947
Epoch 82/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9932 - loss: 0.0354 - val_accuracy: 0.8761 - val_loss: 0.4972
Epoch 83/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9932 - loss: 0.0318 - val_accuracy: 0.8761 - val_loss: 0.5002
Epoch 84/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9977 - loss: 0.0284 - val_accuracy: 0.8761 - val_loss: 0.4990
Epoch 85/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9957 - loss: 0.0275 - val_accuracy: 0.8807 - val_loss: 0.4917
Epoch 86/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9974 - loss: 0.0248 - val_accuracy: 0.8807 - val_loss: 0.4936
Epoch 87/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9958 - loss: 0.0252 - val_accuracy: 0.8807 - val_loss: 0.5020
Epoch 88/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9958 - loss: 0.0196 - val_accuracy: 0.8761 - val_loss: 0.5110
Epoch 89/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9988 - loss: 0.0186 - val_accuracy: 0.8761 - val_loss: 0.5178
Epoch 90/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0221 - val_accuracy: 0.8761 - val_loss: 0.5222
Epoch 91/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0174 - val_accuracy: 0.8761 - val_loss: 0.5266
Epoch 92/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0218 - val_accuracy: 0.8761 - val_loss: 0.5304
Epoch 93/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.0227 - val_accuracy: 0.8761 - val_loss: 0.5353
Epoch 94/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.0179 - val_accuracy: 0.8761 - val_loss: 0.5400
Epoch 95/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0152 - val_accuracy: 0.8761 - val_loss: 0.5445
Epoch 96/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0175 - val_accuracy: 0.8761 - val_loss: 0.5467
Epoch 97/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.0170 - val_accuracy: 0.8761 - val_loss: 0.5505
Epoch 98/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.0157 - val_accuracy: 0.8761 - val_loss: 0.5550
Epoch 99/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0157 - val_accuracy: 0.8761 - val_loss: 0.5604
Epoch 100/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.0130 - val_accuracy: 0.8761 - val_loss: 0.5657
Epoch 101/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0135 - val_accuracy: 0.8761 - val_loss: 0.5693
Epoch 102/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0155 - val_accuracy: 0.8761 - val_loss: 0.5701
Epoch 103/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0187 - val_accuracy: 0.8761 - val_loss: 0.5729
Epoch 104/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0160 - val_accuracy: 0.8716 - val_loss: 0.5774
Epoch 105/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0162 - val_accuracy: 0.8716 - val_loss: 0.5819
Epoch 106/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0120 - val_accuracy: 0.8716 - val_loss: 0.5861
Epoch 107/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0117 - val_accuracy: 0.8716 - val_loss: 0.5894
Epoch 108/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0145 - val_accuracy: 0.8670 - val_loss: 0.5931
Epoch 109/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.0132 - val_accuracy: 0.8670 - val_loss: 0.5980
Epoch 110/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0148 - val_accuracy: 0.8716 - val_loss: 0.6007
Epoch 111/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.0101 - val_accuracy: 0.8716 - val_loss: 0.6029
Epoch 112/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0089 - val_accuracy: 0.8670 - val_loss: 0.6056
Epoch 113/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.0107 - val_accuracy: 0.8670 - val_loss: 0.6084
Epoch 114/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0114 - val_accuracy: 0.8670 - val_loss: 0.6121
Epoch 115/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0106 - val_accuracy: 0.8670 - val_loss: 0.6158
Epoch 116/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.0115 - val_accuracy: 0.8670 - val_loss: 0.6194
Epoch 117/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0112 - val_accuracy: 0.8670 - val_loss: 0.6222
Epoch 118/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0106 - val_accuracy: 0.8670 - val_loss: 0.6258
Epoch 119/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0098 - val_accuracy: 0.8670 - val_loss: 0.6297
Epoch 120/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0115 - val_accuracy: 0.8670 - val_loss: 0.6346
Epoch 121/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0090 - val_accuracy: 0.8670 - val_loss: 0.6397
Epoch 122/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0096 - val_accuracy: 0.8670 - val_loss: 0.6458
Epoch 123/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 0.8670 - val_loss: 0.6517
Epoch 124/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0077 - val_accuracy: 0.8670 - val_loss: 0.6582
Epoch 125/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.0071 - val_accuracy: 0.8670 - val_loss: 0.6621
Epoch 126/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0066 - val_accuracy: 0.8670 - val_loss: 0.6667
Epoch 127/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.8670 - val_loss: 0.6704
Epoch 128/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0072 - val_accuracy: 0.8670 - val_loss: 0.6739
Epoch 129/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0078 - val_accuracy: 0.8670 - val_loss: 0.6785
Epoch 130/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0069 - val_accuracy: 0.8670 - val_loss: 0.6819
Epoch 131/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.8670 - val_loss: 0.6846
Epoch 132/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.8670 - val_loss: 0.6880
Epoch 133/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.8670 - val_loss: 0.6922
Epoch 134/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.8670 - val_loss: 0.6964
Epoch 135/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0059 - val_accuracy: 0.8670 - val_loss: 0.7005
Epoch 136/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.8670 - val_loss: 0.7043
Epoch 137/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0068 - val_accuracy: 0.8670 - val_loss: 0.7071
Epoch 138/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0059 - val_accuracy: 0.8670 - val_loss: 0.7104
Epoch 139/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.8670 - val_loss: 0.7136
Epoch 140/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.8670 - val_loss: 0.7178
Epoch 141/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0055 - val_accuracy: 0.8670 - val_loss: 0.7220
Epoch 142/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.8670 - val_loss: 0.7254
Epoch 143/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.8670 - val_loss: 0.7289
Epoch 144/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.8670 - val_loss: 0.7310
Epoch 145/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.8670 - val_loss: 0.7335
Epoch 146/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.8670 - val_loss: 0.7369
Epoch 147/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.8670 - val_loss: 0.7404
Epoch 148/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.8670 - val_loss: 0.7443
Epoch 149/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.8670 - val_loss: 0.7467
Epoch 150/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.8670 - val_loss: 0.7504
Epoch 151/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.8670 - val_loss: 0.7532
Epoch 152/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.8670 - val_loss: 0.7557
Epoch 153/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.8670 - val_loss: 0.7581
Epoch 154/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.8670 - val_loss: 0.7609
Epoch 155/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.8670 - val_loss: 0.7643
Epoch 156/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.8670 - val_loss: 0.7668
Epoch 157/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.8670 - val_loss: 0.7695

In [36]:
best_val_accuracy = max(model_history.history['val_accuracy'])
print(f"Highest validation accuracy: {best_val_accuracy}")

Highest validation accuracy: 0.8807339668273926

In [37]:
best_train_accuracy = max(model_history.history['accuracy'])
print(f"Highest training accuracy: {best_train_accuracy}")

Highest training accuracy: 0.9660633206367493