<a href="https://colab.research.google.com/github/Trexroy1010/Machiene-Learning-Projects/blob/main/tweet_classification_without_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
import pandas as pd

In [51]:
df = pd.read_csv('/content/ai_human_content_detection_dataset.csv')

In [52]:
df.head()

,text_content,content_type,word_count,character_count,sentence_count,lexical_diversity,avg_sentence_length,avg_word_length,punctuation_ratio,flesch_reading_ease,gunning_fog_index,grammar_errors,passive_voice_ratio,predictability_score,burstiness,sentiment_score,label
0,Score each cause. Quality throughout beautiful...,academic_paper,288,1927,54,0.9514,5.33,5.69,0.0280,53.08,7.41,1,0.1041,105.86,0.5531,0.2034,1
1,Board its rock. Job worker break tonight coupl...,essay,253,1719,45,0.9723,5.62,5.80,0.0262,50.32,8.10,6,0.2045,100.29,0.5643,0.4854,1
2,Way debate decision produce. Dream necessary c...,academic_paper,420,2849,75,0.9071,5.60,5.79,0.0263,46.86,7.86,5,0.2308,96.88,0.4979,-0.2369,1
3,Story turn because such during open model. Tha...,creative_writing,196,1310,34,0.9592,5.76,5.69,0.0260,53.80,7.00,2,0.1912,88.79,0.6241,NaN,1
4,Place specific as simply leader fall analysis....,news_article,160,1115,28,0.9688,5.71,5.97,0.0251,44.53,8.29,0,0.1318,26.15,0.2894,NaN,1

In [53]:
df.isnull().sum()

text_content             0
content_type             0
word_count               0
character_count          0
sentence_count           0
lexical_diversity        0
avg_sentence_length      0
avg_word_length          0
punctuation_ratio        0
flesch_reading_ease     79
gunning_fog_index       35
grammar_errors           0
passive_voice_ratio     31
predictability_score     0
burstiness               0
sentiment_score         54
label                    0
dtype: int64

In [54]:
columns_tofill =df.iloc[:,2:16]

In [55]:
means = columns_tofill.mean()

In [56]:
df.iloc[:,2:16] = df.iloc[:,2:16].fillna(means)

In [57]:
from sklearn.svm import SVC

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X = df.iloc[:,2:16]
y = df['label']

In [60]:
columns_to_fill = X_train.iloc[:, 2:16]
means = columns_to_fill.mean()

# 2. Fill the NaN values in X_train using these means.
X_train.iloc[:, 2:16] = X_train.iloc[:, 2:16].fillna(means)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)

In [62]:
model = SVC()
model.fit(X_train,y_train)

SVC()

In [63]:
accuracy = model.score(X_test, y_test)

In [64]:
print(accuracy)

0.44282238442822386

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [66]:
model2 = RandomForestClassifier(n_estimators = 1000 , random_state = 101)

In [67]:
model2.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000, random_state=101)

In [68]:
y_pred = model2.predict(X_test)

In [69]:
score2 = model2.score(X_test, y_test)

In [70]:
print(score2)

0.51338199513382

In [71]:
from sklearn.metrics import accuracy_score
accuracy2 = accuracy_score(y_test, y_pred)

In [73]:
print(accuracy2)

0.51338199513382